# Generated by Django 4.1.7 on 2023-02-28 19:10

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('candidate', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-posta adresi')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('role', models.BooleanField(choices=[(0, 'İşarayan'), (1, 'İşveren')], default=0, verbose_name='Kullanıcı Grubu')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
        ),
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True, verbose_name='Başlık')),
                ('title_de', ckeditor.fields.RichTextField(blank=True, verbose_name='Başlık Almanca')),
                ('about', ckeditor.fields.RichTextField(blank=True, verbose_name='Hakkında')),
                ('about_de', ckeditor.fields.RichTextField(blank=True, verbose_name='Hakkında Almanca')),
                ('about_alt', ckeditor.fields.RichTextField(blank=True, verbose_name='Hakkında(tam genişlik)')),
                ('about_alt_de', ckeditor.fields.RichTextField(blank=True, verbose_name='Hakkında(tam genişlik) Almanca')),
                ('signf', models.FileField(blank=True, null=True, upload_to='uploads/about/', verbose_name='İmza')),
                ('img_url', models.FileField(blank=True, null=True, upload_to='uploads/about/', verbose_name='Görsel')),
                ('role', models.BooleanField(choices=[(0, 'İşarayan'), (1, 'İşveren')], default=0, verbose_name='Kullanıcı Grubu')),
                ('isActive', models.BooleanField(choices=[(False, 'Yayında Değil'), (True, 'Yayında')], default=False, verbose_name='Yayın Durumu')),
            ],
            options={
                'verbose_name': 'Hakkında',
                'verbose_name_plural': 'Hakkında',
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('content_de', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('role', models.BooleanField(choices=[(0, 'İşarayan'), (1, 'İşveren')], verbose_name='Kullanıcı Grubu')),
            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'İletişimler',
            },
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(verbose_name='Başlık')),
                ('title_de', ckeditor.fields.RichTextField(verbose_name='Başlık Almanca')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='İçerik')),
                ('text_de', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='İçerik Almanca')),
                ('text_short', ckeditor.fields.RichTextField(verbose_name='Kısa Metin')),
                ('text_short_de', ckeditor.fields.RichTextField(verbose_name='Kısa Metin Almanca')),
                ('slug', models.CharField(max_length=200, verbose_name='Slug')),
                ('img_url', models.FileField(upload_to='services/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='Görsel')),
                ('pdf', models.FileField(upload_to='services/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF')),
                ('role', models.BooleanField(choices=[(0, 'İşarayan'), (1, 'İşveren')], default=0, verbose_name='Kullanıcı Grubu')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=200, verbose_name='E-Posta')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('address', models.CharField(max_length=300, verbose_name='Adres')),
                ('youtube_url', models.CharField(max_length=300, verbose_name='YouTube')),
                ('linkedin_url', models.CharField(max_length=300, verbose_name='Linkedin')),
                ('logo', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])], verbose_name='Logo')),
                ('logo_width', models.IntegerField(default=200, verbose_name='Logo genişliği')),
                ('kvkk', ckeditor.fields.RichTextField(blank=True, verbose_name='Kvkk Metni')),
                ('cerez', ckeditor.fields.RichTextField(blank=True, verbose_name='Çerez Politikası Metni')),
                ('role', models.BooleanField(choices=[(0, 'İşarayan'), (1, 'İşveren')], verbose_name='Kullanıcı Grubu')),
            ],
            options={
                'verbose_name': 'Ayarlar',
                'verbose_name_plural': 'Ayarlar',
            },
        ),
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Onay Aşaması'), ('1', 'Aday'), ('2', 'Seçildi'), ('3', 'Tamamlandı')], max_length=50, verbose_name='Durum')),
                ('candidates', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.candidatemodel', verbose_name='Aday')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İşveren')),
            ],
            options={
                'verbose_name': 'Durum',
                'verbose_name_plural': 'Durumlar',
            },
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(blank=True, verbose_name='Başlık')),
                ('title_de', ckeditor.fields.RichTextField(blank=True, verbose_name='Başlık Almanca')),
                ('img_url', models.FileField(blank=True, null=True, upload_to='blog/', verbose_name='Görsel')),
                ('pdf', models.FileField(blank=True, upload_to='blog/pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='İçerik')),
                ('text_de', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='İçerik Almanca')),
                ('text_short', ckeditor.fields.RichTextField(verbose_name='Kısa içerik')),
                ('text_short_de', ckeditor.fields.RichTextField(verbose_name='Kısa içerik Almanca')),
                ('created_at', models.DateField(verbose_name='Yayın Tarihi')),
                ('slug', models.CharField(max_length=200, verbose_name='Slug')),
                ('slug_de', models.CharField(max_length=200, verbose_name='Slug Almanca')),
                ('role', models.BooleanField(choices=[(0, 'İşarayan'), (1, 'İşveren')], verbose_name='Kullanıcı Grubu')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog yazısı',
                'verbose_name_plural': 'Blog yazıları',
            },
        ),
    ]
