# Generated by Django 4.1.7 on 2023-02-28 19:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='text_short',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Kısa içerik'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title_de',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Başlık Almanca'),
        ),
    ]
